kind: pipeline
type: kubernetes
name: default

steps:
  - name: unit-testing
    image: python:3.7-stretch
    commands:
      - echo "Install dependencies"
      - apt-get update
      - apt-get install default-jdk -y
      - pip install -r unit-requirements.txt
      - pip install -e .
      - echo "Launching unit tests"
      - pytest tests/unit

  - name: integration-testing
    image: python:3.7-stretch
    commands:
      - echo "Install dependencies"
      - pip install -r unit-requirements.txt
      - pip install -e .
      - echo "Deploying tests"
      - dbx deploy --jobs={project_name}-integration-test --files-only
      - echo "Running tests"
      - dbx launch --job={project_name}-integration-test --as-run-submit --trace

  - name: release
    image: python:3.7-stretch
    commands:
      - echo "Install dependencies"
      - pip install -r unit-requirements.txt
      - pip install -e .
      - echo "Deploying Job"
      - dbx deploy --jobs={project_name}-sample
    when:
      branch:
        - master